// record-join: the report never fabricates — an empty tree yields NOT CHECKED rows and no crash;
// the provider mode is decided from the binary's bytes; the page carries the legend.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, writeFileSync, rmSync, chmodSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { gather, providerMode, spec } from './record-join.mjs';

test('an empty tree: every row is NOT CHECKED, the change is flagged, nothing throws', async () => {
  const cwd = mkdtempSync(join(tmpdir(), 'join-empty-'));
  try {
    const j = await gather('CHG-0000', { cwd, env: {} , obligationId: 'OB-X-Y-001' });
    assert.equal(j.provider, 'not mounted');
    assert.ok(j.rows.length >= 10);
    assert.ok(j.rows.every((r) => r.status === 'NOT CHECKED'), j.rows.filter((r) => r.status !== 'NOT CHECKED').map((r) => r.field).join(','));
    assert.ok(j.flagged.some((f) => /OB-X-Y-001/.test(f)));
    const s = spec(j);
    assert.equal(s.sections[0].heading, 'Legend');
    assert.ok(s.subtitle.includes('FLAGGED'));
  } finally { rmSync(cwd, { recursive: true, force: true }); }
});

test('providerMode reads the binary: the fake is SIMULATED, anything else LIVE', () => {
  const dir = mkdtempSync(join(tmpdir(), 'join-bin-'));
  try {
    const fake = join(dir, 'kosli');
    writeFileSync(fake, '#!/usr/bin/env node\n// GENERATED by core/kosli-fake.mjs — a record-and-replay double for the kosli CLI. Not Kosli.\n');
    chmodSync(fake, 0o755);
    assert.equal(providerMode({ KOSLI_BIN: fake }), 'SIMULATED');
    const real = join(dir, 'kosli-real');
    writeFileSync(real, '#!/bin/sh\necho real\n');
    assert.equal(providerMode({ KOSLI_BIN: real }), 'LIVE');
    assert.equal(providerMode({}), 'LIVE');
  } finally { rmSync(dir, { recursive: true, force: true }); }
});
