// The join — ONE inspectable record from the institution's mandate to the external record
// (docs/plans/kosli-founder-demo-briefing.md, "For one synthetic change, make the join
// inspectable: mandate ID, obligation ID, control-catalog version/hash, change/commit, artifact
// fingerprint, check result, authenticated producer, applicable approval and external record
// reference"). Every one of those fields already exists somewhere in the tree or at the provider;
// nothing printed them side by side. This script does, and says for EACH row what kind of
// evidence it is — the briefing's legend, applied per field rather than per page:
//
//   VERIFIED    re-checked here: a signature that verifies against the issuers registry, a digest
//               recomputed from bytes, an id the provider resolved on this run
//   DECLARED    read from a governed file in the tree (an envelope, a register, a manifest);
//               true because the file says so and its gate accepts it, not independently proven
//   RESOLVED    the mounted provider answered for it on this run — LIVE if the binary is the
//               official CLI, SIMULATED if it is the record-and-replay fake (core/kosli-fake.mjs)
//   NOT CHECKED the provider is not mounted, or the field is absent
//
// It reuses what record-audit.mjs already gathers (the kept envelopes and their verdicts) and adds
// the obligation, the mandate, the catalog digest, the artifact and the approval. It is a REPORT:
// exit 0 whether or not rows are flagged, because the point is to inspect, not to gate — the
// gates that decide are named on every row.
//
//   node scripts/record-join.mjs <CHG-id> [--obligation OB-id] [--out dir] [--json]
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';
import process from 'node:process';
import { loadIssuers, loadRegistry, resolve as resolveRecord, status as recordStatus } from '../core/external-record.mjs';
import { canonicalEnvelopePayload } from '../core/provenance.mjs';
import { verifySignatureOver } from '../core/attestations.mjs';
import { loadObligations } from '../core/record-controls.mjs';
import { gather as gatherAudit } from './record-audit.mjs';
import { render } from '../discovery/render/render.mjs';
import { parseTokens } from '../discovery/render/tokens.mjs';

const readJson = (p) => { try { return JSON.parse(readFileSync(p, 'utf8')); } catch { return null; } };
const sha256 = (bytes) => createHash('sha256').update(bytes).digest('hex');
const short = (s, n = 12) => (typeof s === 'string' && s ? `${s.slice(0, n)}…` : '—');

/** Is the mounted provider binary the record-and-replay fake? Decided from the file, not from a flag. */
export function providerMode(env = process.env) {
  const bin = env.KOSLI_BIN;
  if (bin && existsSync(bin)) { try { if (/GENERATED by core\/kosli-fake\.mjs/.test(readFileSync(bin, 'utf8'))) return 'SIMULATED'; } catch { /* binary */ } }
  return 'LIVE';
}

/**
 * Gather the join. Pure over `cwd` and `env`; the provider is read through the seam.
 * Returns { changeId, obligationId, rows: [{ field, value, status, source }], flagged: [] }.
 */
export async function gather(changeId, { cwd = process.cwd(), env = process.env, obligationId = null } = {}) {
  const rows = [];
  const flagged = [];
  const row = (field, value, status, source) => rows.push({ field, value: value ?? '—', status, source });
  const g = await gatherAudit(changeId, { cwd });
  const st = recordStatus(cwd);
  const mode = st.mounted ? providerMode(env) : null;
  const provider = st.mounted ? `${st.provider} (${mode})` : 'not mounted';

  // 1. The mandate — the accountable executive's reference, from the operating model.
  const om = readJson(join(cwd, 'docs/governance/operating-model.json'));
  const ae = om?.accountable_executive || {};
  row('mandate', ae.mandate_ref ? `${ae.mandate_ref} · accountable executive ${ae.identity_id || '—'}` : null, ae.mandate_ref ? 'DECLARED' : 'NOT CHECKED', 'docs/governance/operating-model.json · gate OPERATING-MODEL');

  // 2. The obligation — from the register, by id or by the first entry citing a control the change's records evidence.
  const reg = loadObligations(cwd);
  let ob = null;
  if (reg) ob = obligationId ? reg.byId.get(obligationId) || null : reg.obligations[0] || null;
  if (obligationId && !ob) flagged.push(`obligation ${obligationId} is not in docs/governance/obligations.json`);
  row('obligation', ob ? `${ob.id} — ${ob.title}` : null, ob ? 'DECLARED' : 'NOT CHECKED', 'docs/governance/obligations.json · gate OBLIGATIONS');
  row('obligation source', ob ? `${ob.source} · ${ob.article || '—'} · owner ${ob.owner_role}${ob.illustrative ? ' · ILLUSTRATIVE' : ''}` : null, ob ? 'DECLARED' : 'NOT CHECKED', 'docs/governance/obligations.json');
  const catalogControls = ob?.catalog_controls || [];
  row('controls answering it', ob ? `register ${(ob.control_ids || []).join(', ') || '—'} → catalog ${catalogControls.join(', ') || '—'}` : null, ob ? 'DECLARED' : 'NOT CHECKED', 'obligations register → data-risk register → control catalog');

  // 3. The catalog, by digest — and whether the compiled route policy was compiled from this one.
  const catPath = ['docs/governance/control-catalog.json', 'control-catalog.json'].map((p) => join(cwd, p)).find(existsSync);
  const catBytes = catPath ? readFileSync(catPath) : null;
  const catDigest = catBytes ? sha256(catBytes) : null;
  const policy = readJson(join(cwd, 'docs/governance/record-policy.json'));
  const policyAgrees = policy?.catalog_sha256 && catDigest ? policy.catalog_sha256 === catDigest : null;
  row('control catalog', catDigest ? `sha256:${catDigest}${policyAgrees === null ? '' : policyAgrees ? ' · route policy compiled from this catalog' : ' · ROUTE POLICY COMPILED FROM ANOTHER CATALOG'}` : null, catDigest ? 'VERIFIED' : 'NOT CHECKED', 'recomputed from bytes · gates CATALOG, RECORD-POLICY');
  if (policyAgrees === false) flagged.push('record-policy.json was compiled from a different catalog digest');
  const cat = catBytes ? JSON.parse(catBytes.toString('utf8')) : null;
  const ctl = cat?.controls?.find((c) => catalogControls.includes(c.control_id)) || null;
  row('executable check', ctl ? `${ctl.control_id} → ${ctl.mechanism_ref || '—'} (state ${ctl.state}, lane ${ctl.lane || 'pr'})` : null, ctl ? 'DECLARED' : 'NOT CHECKED', 'docs/governance/control-catalog.json');

  // 4. The change, its compiled route and the commit.
  const e = g.envelope || {};
  row('change', e.change_id ? `${e.change_id} · ${e.change_type || '—'} · tier ${e.risk_tier || '—'} · state ${e.current_state || '—'}` : null, e.change_id ? 'DECLARED' : 'NOT CHECKED', `docs/governance/changes/${changeId}/change-envelope.json · gate CHANGE-ENVELOPE`);
  row('compiled route', g.plan?.plan_hash ? `plan ${g.plan.plan_hash} · profiles ${(g.plan.profiles || e.required_profiles || []).join(', ')}` : null, g.plan?.plan_hash ? 'DECLARED' : 'NOT CHECKED', 'control-plan.json · recompiled by the change-envelope gate');
  let head = null; try { head = execFileSync('git', ['rev-parse', 'HEAD'], { cwd, encoding: 'utf8' }).trim(); } catch { /* not a checkout */ }
  const m = g.manifest || {};
  row('commit', m.release_commit ? `${m.release_commit}${head ? head === m.release_commit ? ' · = HEAD' : ` · HEAD is ${short(head)}` : ''}` : head, m.release_commit ? (head === m.release_commit ? 'VERIFIED' : 'DECLARED') : head ? 'VERIFIED' : 'NOT CHECKED', 'evidence manifest release_commit vs git rev-parse HEAD');

  // 5. The artifact.
  const subject = readJson(join(cwd, 'docs/governance/release-subject.json'));
  row('artifact', subject?.artifact?.digest ? `${subject.artifact.name || subject.artifact.uri || 'artifact'} · ${subject.artifact.digest}` : null, subject?.artifact?.digest ? 'DECLARED' : 'NOT CHECKED', 'docs/governance/release-subject.json · gate RELEASE-SUBJECT (written by the build job in CI)');

  // 6. The check result — the kept envelope for the obligation's control, signature re-verified here.
  const issuers = loadIssuers(cwd);
  const registry = loadRegistry(cwd);
  const recordsDir = join(cwd, 'docs/governance/evidence/records');
  let kept = null;
  if (ctl && existsSync(recordsDir)) {
    const name = `gate.${String(ctl.mechanism_ref || '').replace(/\.mjs$/, '').replace(/[\\/]/g, '-')}`;
    const p = join(recordsDir, `${changeId}-${name}.json`);
    kept = existsSync(p) ? readJson(p) : null;
  }
  if (kept) {
    const sig = verifySignatureOver(canonicalEnvelopePayload(kept), kept.attestation, issuers, 'record');
    row('check result', `${kept.payload?.gate || '—'} → ${kept.payload?.result || '—'} · compliant ${kept.compliant} · produced ${kept.produced_at}`, 'VERIFIED', `kept envelope ${kept.name} · re-run by gate-runner, result from the tool (PR1)`);
    row('record carries', `obligations ${JSON.stringify(kept.controls?.institution || [])} · catalog ${JSON.stringify(kept.controls?.catalog || [])} · source ${kept.controls?.controls_source || '—'}`, 'DECLARED', 'core/record-controls.mjs filled from the register — never typed');
    const actor = kept.actor || {};
    const inReg = registry?.identities?.some((i) => i.id === actor.id);
    row('producer (actor)', `${actor.id || '—'} · ${actor.kind || '—'}${actor.model ? ` · model ${actor.model.model_id}` : ''}${inReg ? ' · in identities.json' : ' · NOT IN REGISTRY'}`, inReg ? 'DECLARED' : 'NOT CHECKED', 'signed actor record (K4) — legible, not independently authenticated');
    row('producer (runner)', kept.runner ? `${kept.runner.subject} @ ${short(kept.runner.sha, 10)}` : null, kept.runner ? 'DECLARED' : 'NOT CHECKED', 'PR6 — from the CI environment; platform-verified OIDC is question 3 (kosli-surface.md)');
    row('signature', sig.length ? `FAILS: ${sig[0]}` : `verifies · issuer ${kept.attestation?.issuer}`, sig.length ? 'NOT CHECKED' : 'VERIFIED', 'ed25519 over the canonical envelope, issuer in attestation-issuers.json');
    if (sig.length) flagged.push(`kept record ${kept.name}: ${sig[0]}`);
    if (kept.controls?.institution && ob && !kept.controls.institution.includes(ob.id)) flagged.push(`kept record ${kept.name} does not cite ${ob.id}`);
    // The record at the provider, by id.
    if (kept.record?.id && st.mounted) {
      const r = await resolveRecord({ provider: st.provider, id: kept.record.id, flow: kept.subject?.flow, trail: kept.subject?.trail, name: kept.name }, { cwd, env });
      const held = r.status === 'resolved';
      row('external record (check)', `${st.provider}:${kept.subject?.trail}:${kept.name}#${kept.record.id} · ${held ? `held${r.record?.html_url ? ` · ${r.record.html_url}` : ''}` : `${r.status}: ${r.reason}`}`, held ? `RESOLVED · ${mode}` : 'NOT CHECKED', 'core/external-record.mjs resolve → get attestation');
      if (!held) flagged.push(`the provider did not resolve ${kept.record.id}: ${r.reason}`);
    } else row('external record (check)', kept.record ? `${kept.record.status}${kept.record.id ? ` as ${kept.record.id}` : ''}` : null, st.mounted ? 'DECLARED' : 'NOT CHECKED', st.mounted ? 'post result on the kept envelope; no id to resolve' : 'provider not mounted');
  } else {
    row('check result', ctl ? 'no kept envelope for this control — run core/gate-runner.mjs --record' : null, 'NOT CHECKED', 'docs/governance/evidence/records/');
    if (ctl) flagged.push(`no kept record for ${ctl.control_id}`);
  }

  // 7. The approval — what the tree says, and what it does not prove.
  const hist = Array.isArray(e.state_history) ? e.state_history : [];
  const ptd = hist.find((h) => h.state === 'permission-to-develop');
  const who = ptd ? registry?.identities?.find((i) => i.id === ptd.by) : null;
  row('approval', ptd ? `permission-to-develop by ${ptd.by}${who ? ` (${who.kind}${(who.roles || []).length ? `, ${who.roles.join('/')}` : ''})` : ' (NOT IN REGISTRY)'} at ${ptd.at}` : null, ptd && who?.kind === 'human' ? 'DECLARED' : 'NOT CHECKED', 'envelope state_history · a registry-resolved human, NOT an authenticated identity-provider assertion (approval-attestation-example is that)');

  // 8. The seal anchor — the audit package already decided whether the provider holds it.
  row('external record (seal anchor)', m.external_record ? `${m.external_record.provider}:${m.external_record.id} · ${g.anchorHeld === true ? 'held by the provider' : g.anchorHeld === false ? 'NOT on the provider\'s trail' : 'not checked'}` : null, g.anchorHeld === true ? `RESOLVED · ${mode}` : 'NOT CHECKED', 'evidence manifest external_record · gate HG-0003 (evidence-seal-check)');
  for (const f of g.flagged) flagged.push(`audit: ${f}`);

  return { changeId, obligationId: ob?.id || null, provider, mode, rows, flagged };
}

export function spec(j) {
  return {
    title: `The join — ${j.changeId}${j.obligationId ? ` · ${j.obligationId}` : ''}`,
    subtitle: `mandate → obligation → control → change → commit → artifact → check → producer → approval → external record (${j.provider}) · ${j.flagged.length ? `${j.flagged.length} row(s) FLAGGED` : 'no flags'}`,
    sections: [
      { heading: 'Legend', blocks: [{ table: { headers: ['status', 'meaning'], rows: [
        ['VERIFIED', 're-checked here: a signature verified against the issuers registry, a digest recomputed from bytes, a commit compared to HEAD'],
        ['DECLARED', 'read from a governed file the tree holds; accepted by its gate, not independently proven'],
        ['RESOLVED · LIVE', 'the official CLI answered for it against an org on this run'],
        ['RESOLVED · SIMULATED', 'the record-and-replay fake answered (core/kosli-fake.mjs) — proves the harness, never Kosli'],
        ['NOT CHECKED', 'absent, unmounted, or the field could not be verified'],
      ] } }] },
      { heading: 'One change, one obligation, one record', blocks: [{ table: { headers: ['field', 'value', 'status', 'where it comes from'], rows: j.rows.map((r) => [r.field, String(r.value), r.status, r.source]) } }] },
      { heading: 'What this page does not say', blocks: [{ note: 'A DECLARED actor is legible, not authenticated; a RESOLVED record proves the provider holds the id, not that the assertion is true; a passing check validates a declaration and a recorded test, not a running payment. The authoritative sources for authorisation, settlement and customer outcome are separate.' }, ...(j.flagged.length ? [{ table: { headers: ['flag'], rows: j.flagged.map((f) => [f]) } }] : [])] },
    ],
  };
}

export async function main(argv = process.argv.slice(2), cwd = process.cwd()) {
  const changeId = argv.find((a) => !a.startsWith('--') && !['--obligation', '--out'].includes(argv[argv.indexOf(a) - 1]));
  if (!changeId) { process.stderr.write('usage: node scripts/record-join.mjs <CHG-id> [--obligation OB-id] [--out dir] [--json]\n'); return 2; }
  const oi = argv.indexOf('--obligation'); const obligationId = oi >= 0 ? argv[oi + 1] : null;
  const j = await gather(changeId, { cwd, obligationId });
  if (argv.includes('--json')) { process.stdout.write(JSON.stringify(j, null, 2) + '\n'); return 0; }
  const w = Math.max(...j.rows.map((r) => r.field.length));
  for (const r of j.rows) process.stdout.write(`  ${r.field.padEnd(w)}  ${r.status.padEnd(22)}  ${r.value}\n`);
  for (const f of j.flagged) process.stdout.write(`  · FLAG ${f}\n`);
  const outI = argv.indexOf('--out');
  if (outI >= 0) {
    const outDir = join(cwd, argv[outI + 1]);
    const brand = parseTokens(join(cwd, 'discovery/brand/design.md'));
    mkdirSync(outDir, { recursive: true });
    const out = join(outDir, `${changeId}.join.html`);
    writeFileSync(out, render('document', spec(j), brand));
    process.stdout.write(`  join → ${out}\n`);
  }
  return 0;
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) main().then((c) => process.exit(c));
