import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,readFileSync,rmSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {createHash} from 'node:crypto';
import {buildKit,summarizePilot,protocol,protocolDigest} from './onboarding-pilot.mjs';
import {loadSources} from '../plugins/middleleap-loom/skills/loom-adopt/harness/intake/build-questionnaire.mjs';
import {previewImport,applyImport} from '../plugins/middleleap-loom/skills/loom-adopt/harness/intake/record.mjs';
const base=()=>({schema:'loom.pilot-observations/v1',mode:'observed',protocol_digest:protocolDigest,round:'test',candidate_questionnaire_digest:'sha256:'+'1'.repeat(64),sessions:[]});
function complete(){const data=base();let id=0;for(const role of protocol.roles){id++;for(const cohort of ['first','second']){const tasks=protocol.tasks.filter(t=>t.roles.includes(role)&&t.cohorts.includes(cohort));if(tasks.length)data.sessions.push({participant_id:`P${id}`,role,cohort,unfamiliar:true,attempts:tasks.map(t=>({task_id:t.id,outcome:'completed',elapsed_seconds:600,download_seconds:60,waiting_seconds:30,review_seconds:45,assistance_count:0,repeated_fields:cohort==='first'?4:1,lost_answers:0,readiness_correct:true,false_ready:false,evidence_ref:'synthetic-test-note'}))});}}return data;}
test('empty and synthetic observations never establish user success',()=>{const empty=summarizePilot(base());assert.equal(empty.unassisted_completion_percent,null);assert.equal(empty.status,'needs-evidence-or-iteration');const fake=complete();fake.mode='synthetic';assert.equal(summarizePilot(fake).observed_attempts,0);assert.equal(summarizePilot(fake).status,'needs-evidence-or-iteration');});
test('missing coverage and not-run tasks cannot disappear from acceptance',()=>{const d=complete();d.sessions.pop();assert.equal(summarizePilot(d).status,'needs-evidence-or-iteration');const r=complete();r.sessions[0].attempts[0]={task_id:'first-artifact',outcome:'not-run'};assert.equal(summarizePilot(r).status,'needs-evidence-or-iteration');});
test('failure, assistance, answer loss and misunderstood readiness remain visible',()=>{const d=complete();const a=d.sessions[0].attempts[0];a.outcome='failed';a.assistance_count=1;const r=summarizePilot(d);assert.ok(r.unassisted_completion_percent<100);assert.equal(r.status,'needs-evidence-or-iteration');a.outcome='completed';a.lost_answers=1;assert.ok(summarizePilot(d).blockers.some(s=>s.includes('Answer loss')));});
test('a fast median cannot hide a slow first-artifact attempt',()=>{const d=complete();d.sessions[0].attempts[0].elapsed_seconds=1500;assert.equal(summarizePilot(d).status,'needs-evidence-or-iteration');});
test('complete declared observations remain descriptive and expose paired reuse',()=>{const r=summarizePilot(complete());assert.equal(r.status,'ready-for-human-review');assert.equal(r.authority,'none');assert.equal(r.first_artifact_median_seconds_excluding_downloads,540);assert.deepEqual(r.paired_team_setup_repeated_field_reductions,[3,3]);});
test('invalid durations, duplicate observations and named participants are rejected',()=>{for(const mutate of [d=>d.protocol_digest='sha256:'+'0'.repeat(64),d=>d.sessions[0].attempts[0].download_seconds=900,d=>d.sessions.push(d.sessions[0]),d=>d.sessions[0].participant_id='Real Person']){const d=complete();mutate(d);assert.throws(()=>summarizePilot(d));}});
test('kit binds actual HTML bytes, supplies valid handoffs and never overwrites observations',t=>{const root=mkdtempSync(join(tmpdir(),'loom-pilot-test-'));t.after(()=>rmSync(root,{recursive:true,force:true}));const dir=join(root,'kit'),kit=buildKit(dir);const bytes=readFileSync(join(dir,'questionnaire.html'));assert.equal(kit.questionnaire_digest,'sha256:'+createHash('sha256').update(bytes).digest('hex'));assert.equal(summarizePilot(JSON.parse(readFileSync(join(dir,'observations.json')))).observed_attempts,0);assert.throws(()=>buildKit(dir),/never overwritten/);const {bank,questions_digest}=loadSources();let state={institution:kit.institution,answers:{},role:'',pack:''};for(const file of ['brand.json','architecture.json']){const record=JSON.parse(readFileSync(join(dir,'fixtures',file)));const plan=previewImport(state,record,bank,questions_digest);assert.deepEqual(plan.errors,[]);state=applyImport(state,record,bank,questions_digest);}assert.ok(state.answers.A1.answer);assert.ok(state.answers.C1.answer);const conflict=previewImport(state,JSON.parse(readFileSync(join(dir,'fixtures/brand-conflict.json'))),bank,questions_digest);assert.ok(conflict.conflicts.length);});
